# Generated by Django 4.1.5 on 2023-05-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(blank=True, default='blank.webp', upload_to='profile_file'),
        ),
    ]
