# Generated by Django 4.2.1 on 2023-09-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='pdf_name',
            field=models.CharField(default=777, max_length=100),
            preserve_default=False,
        ),
    ]
